xlab-si/xopera-opera

src/opera/parser/tosca/v_1_3/topology_template.py

In the current version (0.5.3) of xOpera, outputs are mandatory. I would suggest a quick fix to make them optional. @tadeboro could you take a look?

Make ouputs optional.

---

src/opera/parser/tosca/__init__.py
tests/opera/parser/test_tosca.py

CSAR archives that contain TOSCA metadata can have a root service template at any depth in the folder hierarchy. Up until now, opera assumed that the service template that contains the topology will be always present at the root of the CSAR, which messed-up the import resolution.
To resolve this, we taught opera about the relative path to the root service template.
Fixes #25

Properly handle nested root template

---

src/opera/commands/__init__.py
src/opera/commands/validate.py

In this commit we bring back the ability to validate TOSCA template from CSAR using `opera validate` command that was removed with 0.5.0 version.
Changes also contain inputs so that validation could also be performed with -i (--inputs) option where the inputs for the service template are checked.

Bring back CSAR service template validation

---

setup.cfg

[PEP420](https://www.python.org/dev/peps/pep-0420/) are Implicit Namespace Packages. Without breaking anything (assuming Python >= 3.3), it allows the `opera` namespace (previously a package) to be extended in other source trees.
Example.
* Create a new project that depends on xopera-opera - `pip install opera==0.5.5`.
* `mkdir -p opera/extension/`
* `touch opera/extension/__init__.py`
* `echo "import opera.commands" > opera/extension/thing.py`
* `python3 -m opera.extension.thing`
* Result
* without PEP420 in this repository: `Error while finding module specification for 'opera.extension.thing' (ModuleNotFoundError: No module named 'opera.extension')`
* with PEP420 in this repository: EOF
To be specific about my needs, I would like to `import opera` in the xOpera API package we're …

Remove the root __init__.py to enable PEP420.

---

src/opera/parser/tosca/__init__.py
src/opera/parser/tosca/v_1_3/service_template.py
tests/opera/parser/test_tosca.py
tests/opera/parser/tosca/test_reference.py
tests/opera/parser/tosca/v_1_3/test_service_template.py

Currently opera throws duplicate key error when importing one template multiple times. This can be fixed by remembering which files have been already imported into the main TOSCA service template.

Add duplicate imports management

---

.circleci/config.yml
Makefile
Pipfile

It's time to update our CI/CD pipeline by introducing changes 
that enable testing of the opera pip package with Python 3.8.
The new addon is also the ability to deploy opera Python package to
PyPI. This part is semi-automated and is invoked only by pushing a new
tag while on master branch.

Add CI/CD Python 3.8 testing and PyPI deploy

---

setup.py

To upload python package to PyPI its version field must be in the
format specified in PEP 440. This means that local component of the
version which comes after version number should be compatible with PEP
440. Publishing opera package to test PyPI instance was currently
failing due to invalid value for version which also included commit
hash(for example '0.5.7.dev2+g69f7164'). Therefore we had to update
setup.py to cut off the commit hash from the local component of the
version during the build process so that version can become valid(like
'0.5.7.dev2') and by that our package can be freely uploaded to PyPI.

Update setup.py and thereby fix publishing to test PyPI

---

.circleci/config.yml
Makefile
tests/integration/misc-tosca-types/inputs.yaml
tests/integration/misc-tosca-types/modules/artifact_types/test/test.yaml
tests/integration/misc-tosca-types/modules/capability_types/test/test.yaml
tests/integration/misc-tosca-types/modules/data_types/test/test.yaml
tests/integration/misc-tosca-types/modules/group_types/test/test.yaml
tests/integration/misc-tosca-types/modules/interface_types/test/test.yaml
tests/integration/misc-tosca-types/modules/node_types/file/file.yaml
tests/integration/misc-tosca-types/modules/node_types/file/playbooks/create.yaml
tests/integration/misc-tosca-types/modules/node_types/file/playbooks/delete.yaml
tests/integration/misc-tosca-types/modules/node_types/hello/hello.yaml
tests/integration/misc-tosca-types/modules/node_types/hello/playbooks/create.yaml
tests/integration/misc-tosca-types/modules/node_types/hello/playbooks/files/test.txt
tests/integration/misc-tosca-types/modules/node_types/noimpl/noimpl.yaml
tests/integration/misc-tosca-types/modules/node_types/setter/playbooks/create.yaml
tests/integration/misc-tosca-types/modules/node_types/setter/setter.yaml
tests/integration/misc-tosca-types/modules/node_types/test/playbooks/create.yaml
tests/integration/misc-tosca-types/modules/node_types/test/test.yaml
tests/integration/misc-tosca-types/modules/policy_types/test/test.yaml
tests/integration/misc-tosca-types/modules/relationship_types/test/playbooks/test.yaml
tests/integration/misc-tosca-types/modules/relationship_types/test/test.yaml
tests/integration/misc-tosca-types/runme.sh
tests/integration/misc-tosca-types/service-template.yaml

With these additions we populate our CI/CD configuration with daily
testing of xOpera python package. This new testing routine will now
occur every night at 3 o'clock and will help us to be sure that the
latest version of the orchestrator is working properly.
CircleCI will trigger a job where the most important opera commands
will be tested. In the very beginning of this worklflow the last
version of opera pip package is installed. This is followed by opera
validate operation and the deployment which is performed on testing
CSAR that includes most common TOSCA definitions. And last but not
least, after the deployment we also look for outputs and later on use
the undeploy command to demolish the deployed solution.

Add first integration tests and daily/nightly xOpera CI/CD package testing

---

README.rst

These changes include some updates for opera's README and more
accurately here we are providing the missing information for the
quickstart section where (although it was evident) it is now specified
that user has to clone the opera's GitHub repository before deploying
the examples within.
cc @cankarm

Update the hello world README example

---

src/opera/commands/deploy.py
src/opera/commands/outputs.py
src/opera/commands/undeploy.py

Within this update we are improving some of opera's commands by adding
the -l (or --location) command line option that brings the possibility
to control the location where opera will store the information about
orchestration and deployment. So with these changes user can now
specify the location of the .opera folder along with opera deploy,
undeploy and outputs commands.
Hitherto xOpera created the aforementioned .opera storage folder in the
current working directory which resulted in the lack of flexibility
when deploying the (same) solutions multiple times. Now there is a
chance to use use the same deployment CSARs with several executions of
opera without any interference. Users will be able to relocate and store
orchestration info to the suitable locations which will also make
those …

Implement the ability to relocate .opera storage folder

---

src/opera/instance/node.py

Given the following node template's definition:
```
route_table-1:
type: steampunk.test.RouteTable
requirements:
- subnet: subnet-1
- subnet: subnet-2
- subnet: subnet-3
```
When I run `opera deploy`, the implementation of my `pre_configure_source` for a particular target gets run more than once. It actually gets run once for each repetition of `subnet` requirement in the list:
```
Deploying route_table-1_0
Executing pre_configure_source on route_table-1_0--subnet-1_0
Executing pre_configure_source on route_table-1_0--subnet-2_0
Executing pre_configure_source on route_table-1_0--subnet-3_0
Executing pre_configure_source on route_table-1_0--subnet-1_0
Executing pre_configure_source on route_table-1_0--subnet-2_0
Executing pre_configure_source on route_table-1_0--subnet-3_0
Executing …
```

The number of each relationship interface's execution should be 1

---

examples/attribute_mapping/playbooks/create-student.yaml
examples/attribute_mapping/playbooks/teacher-teaches-student--preconfigure-source.yaml
examples/attribute_mapping/service.yaml
src/opera/executor/ansible.py
src/opera/instance/base.py
src/opera/instance/node.py
src/opera/instance/relationship.py
src/opera/parser/tosca/v_1_3/collector_mixin.py
src/opera/parser/tosca/v_1_3/operation_definition_for_template.py
src/opera/parser/tosca/v_1_3/operation_definition_for_type.py
src/opera/template/node.py
src/opera/template/operation.py
src/opera/template/relationship.py
tests/unit/opera/instance/test_attribute_mapping.py
tests/unit/opera/parser/tosca/v_1_3/test_operation_definition_for_type.py

*TOSCA Simple Profile in YAML Version 1.3* specifies in Section 3.6.17, that an operation may include keyname `outputs`, which is a map of attribute mappings. This then interpreted as *an optional map of attribute mappings that specify named operation output values and their mappings onto attributes of the node_type or relationship that contains the interface within which the operation is defined.*
There is an example of usage in Section 2.16.1.
This PR implements the support for this feature. We are now able in each operation to specify a list of key names that the operation's implementation returns at the end of its running. For each key, we can provide a mapping to an attribute that will receive the new value. We support referencing attributes of the current node template's instance in …

Support for attribute mapping in operations

---

src/opera/commands/deploy.py
src/opera/commands/undeploy.py
src/opera/executor/ansible.py
src/opera/instance/node.py
src/opera/instance/topology.py
src/opera/template/operation.py
src/opera/threading/__init__.py
src/opera/threading/node_executor.py
src/opera/threading/utils.py
tests/integration/concurrency/playbooks/sleep.yaml
tests/integration/concurrency/runme.sh
tests/integration/concurrency/service.yaml

In order to improve deployment/undeployment performance, execution is parallelized. In the situation when direct acyclic graph representing the node dependencies can be drawn as a tree with separate branches xOpera runs operations concurrently.
A new parameter "-w" is introduced in order to indicate the maximum number of concurrent threads. If omitted, xOpera executes all operations sequentially.

Implement concurrent deploy/undeploy execution

---

src/opera/parser/tosca/reference.py
src/opera/parser/tosca/v_1_3/policy_definition.py
src/opera/parser/tosca/v_1_3/policy_type.py
tests/integration/misc-tosca-types/service-template.yaml
tests/unit/opera/parser/tosca/v_1_3/test_policy_definition.py
tests/unit/opera/parser/tosca/v_1_3/test_policy_type.py

In this commit we are updating our TOSCA parser with the support for
policy type targets which is an optional list of valid node types or
group types the policy type can be applied to. When used is
node_templates section of the main TOSCA service templates policy
targets represent the optional list of names of node templates or
groups that the actual policy gets applied to. Contents of this
commit are also linked to the issue #32. The only thing that still
needs to be implemented are policy type triggers.

Support targets keyname in policy type definitions

---

src/opera/executor/ansible.py

This commit includes upgrades of our Ansible executor and we can
therefore announce a new supported environment variable called
OPERA_SSH_IDENTITY_FILE which addresses the needs explained in #57.
Till now xOpera orchestrator offered only OPERA_SSH_USER environment
variable which is used by the Ansible executor when establishing the
connection to a remote machine to tell which user someone wants to
connect as. But as time passed by we realized that it could be useful
for the user to be able to choose ssh keys to connect to remote VMs.
This feature relieves the user of managing this part all by himself
since it is know that the situations where users have too many ssh key
files on their machines occur frequently. In this cases just putting
the keys to the ~/.ssh folder is not enough and …

Welcome the support for private ssh key files

---

src/opera/commands/__init__.py
src/opera/commands/deploy.py
src/opera/commands/init.py
src/opera/commands/outputs.py
src/opera/commands/undeploy.py
src/opera/parser/tosca/csar.py
src/opera/storage.py
tests/integration/misc-tosca-types/TOSCA-Metadata/TOSCA.meta
tests/integration/misc-tosca-types/runme.sh

Up until now opera supported deploying uncompressed CSARs, but not the
compressed version of CSAR file. Here we accomplished that opera will
recognize also zip compressed TOSCA template files and will allow to
either deploy or undeploy the service template from CSAR. These
changes are linked to the issue #27 that provided the enhancement.
I have tested these changes locally with:
```console
opera deploy -i inputs.yaml -t service-template.yaml test.csar
opera undeploy -c test.csar
```
If needed I can also provide an integration test with compressed CSAR and those new CLI options.
cc @cankarm  just mentioning you because it was you who filed this issue and because this was one of the important requirements for the the RADON project.

Incorporate the support for compressed CSAR files

---

src/opera/parser/yaml/constructor.py
tests/unit/opera/parser/yaml/test_constructor.py

Seeing duplicate map entries in TOSCA YAML templates can be a problem.
This was spotted in #64 where the runnable TOSCA template example with
two node templates having the same names resides. This example showed
that users can be doomed to conceal that one of the duplicates will be
skipped and the orchestration will continue without any error.
With these changes we tackle the aforementioned issue by updating the
YAML parser. We added the duplicate key checks to the YAML map
constructor and also provided the unit test for this issue.
Fixes #64

Detect duplicates in the YAML maps

---

src/opera/commands/deploy.py
src/opera/commands/init.py
src/opera/commands/outputs.py
src/opera/commands/undeploy.py
src/opera/commands/validate.py
src/opera/storage.py

This will allow clients, e.g. xopera-api, to use this as a nice Python library. I've extracted the actual logic to separate functions and used a different one for CLI parser callbacks. Much cleaner this way :)

Decouple the Python API from CLI interaction.

---

src/opera/commands/deploy.py
src/opera/commands/init.py

Some state writes were left over in CLI handling functions.
I've tested that this works with xopera-api, so I don't think any further changes will be necessary.

Leftover library extraction: state handling

---

src/opera/commands/deploy.py
src/opera/commands/init.py
src/opera/commands/outputs.py
src/opera/commands/undeploy.py
src/opera/commands/validate.py
src/opera/executor/ansible.py
src/opera/instance/base.py
src/opera/instance/node.py
src/opera/instance/topology.py
src/opera/template/node.py
src/opera/template/operation.py
src/opera/template/relationship.py
src/opera/threading/node_executor.py

These changes apply to the #68 issue that expressed the need to give
users more information during the orchestration process. And because
less is not always more we decided to implement a debug mode for opera
which returns more information during the deployment/undeployment
process. This could was done by adding a new optional CLI argument
called --verbose or -v which can be used with opera deploy or opera
undeploy CLI commands. We also prepared verbose CLI option for
all the other remaining opera commands.
If the verbose mode is turned on user will be able to see the outputs
of the Ansible playbook executors and also orchestration inputs. This
will hopefully lead to easier debugging of the orchestration process
and especially the actuators of the orchestration. …

Include verbose mode for opera CLI commands

---

src/opera/commands/deploy.py
src/opera/commands/init.py
src/opera/commands/outputs.py
src/opera/commands/undeploy.py
src/opera/storage.py
src/opera/utils.py

The discussion in #46 showed that it would be necessary to add some
optional arguments to opera deploy command. In this commit we did just
that in order to address the new features which are:
```console
opera deploy -i inputs.yaml service.yaml
opera deploy --resume -i inputs.yaml service.yaml
opera deploy --force -i inputs.yaml service.yaml
```
a) Wise men once said that TOSCA orchestrator should treat each
deployment separately and distinguish it from all other deployments
that have been/would be created before/after. And because opera treats
deployments based on file system storage location (i.e. hidden .opera
folder) we went on and implemented a different deployment behaviour.
So if user tries to deploy again on already deployed instance model an
error is raised telling that deployment …

Add new opera deploy cli command options

---

src/opera/commands/deploy.py
src/opera/commands/init.py
src/opera/commands/undeploy.py

The support for the compressed CSAR files was introduced along with
opera init command in #55. Currently one CSAR can be initialized within
the same working directory and it gets extracted to .opera/csars/csar.
The orchestration processed including CSAR initialization, deployment
and undeployment worked just fine when the linked artifacts (e.g
Ansible playbooks) for TOSCA operation implementations were deeper in
the structure than the runnable TOSCA service template. However, the
problem has arisen when user wanted to link his playbooks from the root
of the CSAR because opera assumed that the current working directory
that CSAR was deployed from, was at the root of the extracted CSAR ,
Till now opera was searching for the linked files in the current
working dir but not in the actual root …

Deploy initialized compressed CSARs from their extracted root

---

examples/artifacts/files/file.txt
examples/artifacts/playbooks/create.yaml
examples/artifacts/service.yaml
src/opera/executor/ansible.py
src/opera/instance/node.py
src/opera/instance/relationship.py
src/opera/parser/tosca/v_1_3/artifact_definition.py
src/opera/parser/tosca/v_1_3/collector_mixin.py
src/opera/parser/tosca/v_1_3/definition_collector_mixin.py
src/opera/parser/tosca/v_1_3/node_template.py
src/opera/template/node.py
src/opera/template/operation.py
src/opera/template/topology.py
src/opera/value.py

Now the time is right to replenish our opera orchestrator with the
support for get_artifact TOSCA function which is generally used to
extract artifact location between modelable TOSCA entities that are
defined within the same service template. The desire for this useful
enhancement has also been the main topic of the issue #59.
The implemented TOSCA artifact function can be useful to link the
prepared orchestration artifacts (e.g. zipped FaaS function files)
directly to a TOSCA service template. Most likely the users will use
get_artifact function when setting the default value for interface
operation inputs and then later on retrieve them during the
orchestration in the Ansible playbook actuators on demand.
With these additions we supported all the parameters defined in TOSCA …

Supplement get_artifact TOSCA function

---

examples/policy_triggers/playbooks/auto_scale.yaml
examples/policy_triggers/playbooks/create.yaml
examples/policy_triggers/playbooks/retrieve_info.yaml
examples/policy_triggers/playbooks/scale_down.yaml
examples/policy_triggers/playbooks/scale_up.yaml
examples/policy_triggers/service.yaml
src/opera/parser/tosca/reference.py
src/opera/parser/tosca/timestamp.py
src/opera/parser/tosca/v_1_3/activity_definition.py
src/opera/parser/tosca/v_1_3/condition_clause_definition.py
src/opera/parser/tosca/v_1_3/event_filter_definition.py
src/opera/parser/tosca/v_1_3/policy_definition.py
src/opera/parser/tosca/v_1_3/policy_type.py
src/opera/parser/tosca/v_1_3/time_interval.py
src/opera/parser/tosca/v_1_3/trigger_definition.py
tests/unit/opera/parser/tosca/test_timestamp.py
tests/unit/opera/parser/tosca/v_1_3/test_activity_definition.py
tests/unit/opera/parser/tosca/v_1_3/test_condition_clause_definition.py
tests/unit/opera/parser/tosca/v_1_3/test_event_filter_definition.py
tests/unit/opera/parser/tosca/v_1_3/test_policy_definition.py
tests/unit/opera/parser/tosca/v_1_3/test_policy_type.py
tests/unit/opera/parser/tosca/v_1_3/test_time_interval.py
tests/unit/opera/parser/tosca/v_1_3/test_trigger_definition.py

The desire for the support of [TOSCA Trigger definitions](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#DEFN_ENTITY_TRIGGER_DEFN) has grown
stronger with opening the #32 issue. At this point we are therefore
introducing the support for parsing TOSCA Policy type triggers which
can be used to define the event, condition and action that is used to
invoke(trigger) a policy it is associated with. These changes also
include unit tests and the runnable TOSCA template example in
`examples/policy_triggers` that contains policies with TOSCA triggers. 
In the implementation part we first targeted to support the standard
trigger definition keynames, but then continued adding the support for
the additional keynames that are used in extended …

Add parsing of TOSCA Policy type triggers

---

src/opera/parser/tosca/v_1_3/operation_definition_for_type.py
tests/integration/misc-tosca-types/modules/node_types/test/test.yaml
tests/integration/misc-tosca-types/modules/relationship_types/test/test.yaml

In this commit we are addressing passing information as inputs to
TOSCA Interfaces and Operations which needed some refactoring as it
was stated in #83. When declaring input variables for all operations on
a single interface opera would have returned and error if user had
forgotten to specify type keyname for input. But the same behaviour was
not applied for declaring input variables for a single operation and
opera proceeded with the orchestration if input type had been left out.
With these changes we are replacing Parameter definition with Property
definition which requires type keyname so that opera now also raises an
exception in the second case.

Refine required fields in interface and operation inputs

---

.circleci/config.yml

After we supplied the very first opera documentation which followed the
issue #47, we have discovered that there are some issues with the
deployment. The CI/CD pipeline failed when there were no new changes
for the sphinx doc files within the merged commit saying that the
working tree is clean and that there was nothing new to commit. Top
prevent these ugly failures we enabled creating empty commits for these
cases by adding --allow-empty flag to the git commit command.

Fix documentation deployment errors when having no changes in docs

---

src/opera/parser/tosca/v_1_3/collector_mixin.py
tests/integration/misc-tosca-types/service-template.yaml

These modifications of code will remove a bug that occurred when there
were different artifact names used in node templates as the ones that
were declared in the corresponding node types. The error also returned
invalid artifacts when there were no artifacts defined in the node
type, but were later added within the node template. Another firm fact
that supports removing these checks is the [TOSCA standard](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/cos01/TOSCA-Simple-Profile-YAML-v1.3-cos01.html#DEFN_ENTITY_ARTIFACT_DEF) itself, which
defines artifacts keyname within node types or templates as a map of
artifact definitions. This means that there are no artifact assignments
within node types that would need to correspond to artifact definitions
within the node …

Removal of needless checks for undeclared artifacts

---

.circleci/config.yml

Here we are applying some changes to the CircleCI config. By adding
some tag filters for the job that pushes the stable branch we want to
ensure that job will be executed. Up until now this job was ignored
by CI/CD due to missing tag/branch filters and the stable branch
received no updates which caused nightly tests to fail.

Fixes for pushing stable branch with CircleCI

---

src/opera/instance/topology.py
src/opera/threading/node_executor.py

Deployment/undeployment do not schedule nodes for execution
unless there are free workers to avoid pending operations. Also upon
error executor tries to cancel pending operations if there are any.

Added fix for concurrent immediate cancellation

---

src/opera/instance/node.py
src/opera/instance/relationship.py
src/opera/template/node.py
src/opera/template/operation.py
src/opera/template/relationship.py
src/opera/template/topology.py
src/opera/value.py

Up until now opera printed "Cannot use an unset value." in case there
was an input defined in the service template but was not set within
inputs.yaml file. There are also other cases for example when you
define a property or attribute within node type without setting its
default value. If you forget to define its value later within the
node_templates section you will get the same error. And since it would
be really useful to know which property/attribute/input causes an issue
in such cases when the data evaluation fails we decided to give more
information to the users by printing also the name of the property.

Increase verbosity when encountering unset values

---

examples/intrinsic_functions/service.yaml
src/opera/instance/node.py
src/opera/instance/relationship.py
src/opera/template/node.py
src/opera/template/topology.py
src/opera/value.py

Within this commit we are adding the support for TOSCA intrinsic
functions which can be useful when manipulating data in TOSCA
templates. The desire to provide this began with issue #86. Then we
implemented parsing and processing of all three intrinsic functions,
which are concat, join and token along with all their parameters.
There is also an example showing how to use these functions along with
opera outputs that can be found in examples/intrinsic_functions.
__________________________________________________________
cc @dradX, @MysteriousWolf

Provide support for the intrinsic TOSCA functions

---

src/opera/commands/deploy.py
src/opera/commands/outputs.py
src/opera/commands/undeploy.py
src/opera/executor/ansible.py
src/opera/instance/base.py
src/opera/instance/node.py
src/opera/instance/topology.py
src/opera/parser/tosca/csar.py
src/opera/storage.py
src/opera/template/node.py
src/opera/template/operation.py
src/opera/template/relationship.py
src/opera/threading/node_executor.py
tests/integration/misc-tosca-types/runme.sh

There was an idea to introduce the deployment the compressed TOSCA
CSAR. In #82 we made sure that initialized CSARs are deployed from
their extracted root which is usually in .opera/csars/csar (other
storage locations can be used instead of .opera by using
--instance-path CLI flag). That's why we forced opera to move to
the extracted csars storage dir before the deployment. However, we
have forgotten one tiny detail - storage instance files. These are
stored in .opera/instances and accessed during the execution. To
prevent the creation of these files in csars/csar subfolder we
ensured that opera goes two levels up in the storage folder structure.
_______________________
The zipped CSAR this can be tested with is here: [test.zip](https://github.com/xlab-si/xopera-opera/files/5161955/test.zi …

Apply various compressed CSAR deployment fixes

---

src/opera/commands/__init__.py
src/opera/commands/info.py
src/opera/instance/topology.py
tests/integration/misc-tosca-types/runme.sh

Within these changes we are bringing a little sunshine. The main
addition is the new opera info command, which is the sixth opera CLI
command in addition to opera validate, init, deploy, undeploy and
outputs. The idea for this command originated from #104, where we
wanted to have an option to inform user about the current opera
project and would allow user to access its storage and state. This
would include printing out the path to TOSCA service template
entrypoint, extracted CSAR location, path to the storage inputs and
status/state of the deployment. The output can be formatted in YAML
or JSON. An example of the latter is shown below.
```json
{
"service_template":  "string | null",
"content_root":      "string | null",
"inputs":            "string | null",
"status": …
```

Summon opera info command

---

examples/artifacts/files/file.json
examples/artifacts/playbooks/create.yaml
examples/artifacts/service.yaml
src/opera/parser/tosca/v_1_3/collector_mixin.py
src/opera/template/node.py

These changes apply mostly to the usage of get_artifact TOSCA function.
Up until now opera used just the artifacts defined within node types
and when addressing them with `get_artifact` everything worked okay.
Fine, right? No, there's more that meets the eye. Artifacts can also be
defined right before the deployment within the node template itself. So
we needed to take those into account too, so that they can be accessed
with `get_artifact` function. Since TOSCA does not specially define
artifact assignments, there is no priority between them. This could
then result in error if user defines the artifact with the same name in
node type and node template. However, TOSCA states that when having
duplicated artifacts, the ones in node template should augment those
that were provided by its …

Use all artifacts when accessing them with get_artifact function

---

src/opera/executor/ansible.py

The issue #89 described the story behind Ansible host key checking and
the fact that there are situations when host checks need to be set to
false. Hitherto, opera disabled strict host key checking within the
Ansible inventory. The changes here provide the ability to disable host
key checking globally (within ansible.cfg) which can be achieved by
using `OPERA_SSH_HOST_KEY_CHECKING` environment variable.

Add an option to disable Ansible host key checking

---

examples/attribute_mapping/service.yaml
examples/nginx_openstack/library/nginx/server/types.yaml
examples/nginx_openstack/library/openstack/vm/types.yaml
examples/policy_triggers/service.yaml
src/opera/parser/tosca/v_1_3/topology_template.py
tests/integration/misc-tosca-types/service-template.yaml
tests/unit/opera/parser/tosca/v_1_3/test_topology_template.py

These significant changes are directly connected to the issue #115. To
sum things up, here we changed the parsing of the TOSCA policies for
the topology_template section. Before this commit, policies were parsed
and represented as a map/dict and after looking at the TOSCA standard,
we soon have found out that we should have used a list. So the TOSCA
parser within the orchestrator was refactored to the point that it
serializes policies as a list. By making this change we also had to
refactor some examples and integration tests.
There is also an additional commit for updating the examples.
________________
Fixes #115.
Connected to https://github.com/radon-h2020/radon-particles/pull/62

Fix policies serialization and refactor examples

---

examples/intrinsic_functions/service.yaml
src/opera/template/node.py
src/opera/template/topology.py

In this commit we apply some refactorings to TOSCA instrinsic functions
based on the problems spotted in #112. There it was discovered that
SELF keyword in TOSCA functions do not work when using them inside
intrinsic functions. Or in other words, we are unable to get node's own
attributes and properties from intrinsic functions used within this
node. The problem originates from the part where we have forgotten that
we the intrinsic functions will not be used only in template's outputs,
but also throughout the whole TOSCA template. Therefore this was
calling for a change where we made sure that node names and their
references are used when calling other TOSCA functions in intrinsic
functions. This does mostly concern concat and join functions as those
two are allowed to have other function …

Use node name references with intrinsic functions

---

tests/integration/misc-tosca-types/modules/relationship_types/test/test.yaml

There is no operation called `configure_target` on the `tosca.interfaces.relationship.Configure` interface type. It should be `pre_configure_target` or `post_configure_target`.

corrected operation name to match interface

---

.circleci/config.yml
Makefile
examples/runme.sh

Where to begin? Tests, examples, more examples in the other repository.
Users can experience a total confusion. But we will not allow this to
happen with opera. That's why we opened #93 issue in order to clean up
the mess and move all the existing opera examples to the integration
test folder. This includes examples in this repository and also the
examples from xopera-examples repository that will not be needed
anymore after this. Since both examples and integration tests contain
runnable TOSCA templates and Ansible playbooks, there is no need to
keep them separated. It would be better to have just the integration
tests so that the features that were currently located only in examples
can be tested within the CI/CD pipelines too. However, it is not that
easy. Some examples require special …

Establish a new CI routine to test the opera examples

---

examples/relationship_outputs/files/file.txt
examples/relationship_outputs/playbooks/create.yaml
examples/relationship_outputs/playbooks/post_configure_source.yaml
examples/relationship_outputs/playbooks/post_configure_target.yaml
examples/relationship_outputs/playbooks/pre_configure_source.yaml
examples/relationship_outputs/playbooks/pre_configure_target.yaml
examples/relationship_outputs/service.yaml
examples/runme.sh
src/opera/instance/base.py
src/opera/instance/node.py
src/opera/instance/relationship.py
src/opera/parser/tosca/v_1_3/topology_template.py
src/opera/template/node.py
src/opera/template/relationship.py
src/opera/template/requirement.py
src/opera/template/topology.py
tests/integration/misc_tosca_types/modules/relationship_types/test/playbooks/test.yaml
tests/integration/misc_tosca_types/modules/relationship_types/test/test.yaml
tests/integration/misc_tosca_types/service-template.yaml
tests/unit/opera/instance/test_attribute_mapping.py

This PR applies changes that correspond to issues #117 and #119.
The changes from the first commit fully resolve the discovered issue that
an operation error is raised when using TOSCA get_input functions
inside the TOSCA relationship types. This can be problematic every time
when user would want to get initial inputs to a relationship.
The modifications in the second commit are based the example where we
were trying to use TOSCA outputs in order to get attributes, properties
or inputs from TOSCA relationship templates. Since this feature is
important and because it is possible to get node template's outputs for
a while now within opera, we wanted to add this for relationships too.
Here we apply some code changes to tell opera that TOSCA outputs can
come from node or relationship …

Relationship types and templates fixes for inputs and outputs

---

src/opera/commands/deploy.py
src/opera/commands/init.py
tests/integration/cli_commands/runme.sh
tests/integration/misc_tosca_types/runme.sh

These changes correspond to the debate within the #107 issue. There we
have agreed that opera init command is unneeded at the moment as it
does not do anything different from opera deploy (apart from just
skipping the last deployment step). We can achieve the same behavior
with opera deploy by adding the compressed CSAR initialization logic.
And that's exactly what we did. Users are now able to deploy TOSCA
service templates, uncompressed CSARs or compressed CSARs with opera
deploy. We thought about the possibility that some users would still
initialize the service template/CSAR first and the deploy, so we kept
the option to run just opera deploy after the initialization.
As opera init command currently has no benefits, we are also applying the
changes that will warn the users that opera …

Mark opera init as deprecated and enable compressed CSAR deployment with opera deploy

---

src/opera/commands/__init__.py
src/opera/commands/deploy.py
src/opera/commands/init.py
src/opera/commands/unpackage.py
src/opera/commands/validate.py
src/opera/parser/tosca/csar.py
src/opera/utils.py
tests/integration/cli_commands/runme.sh
tests/integration/misc_tosca_types/runme.sh

The issue #124 presented the importance of having both, packaging and
unpackaging commands supported within the opera TOSCA orchestrator.
So be it. In this commit we are boosting up opera's CLI commands
by introducing the new opera unpackage command, which will serve for
unpacking (i.e. validating and extracting) the compressed TOSCA CSAR
files. The opera unpackage command receives a compressed CSAR as a
positional argument. It then validates and extracts the CSAR to a
given location. The available command switches are:
1. --destination/-d is the folder location where the CSAR will be
extracted to. If the specified path does not exists, it will be
created during the unpackaging process. The flag can be omitted
and this means that the output dir will be named using UUID.
2. --format/-f is …

Equip opera CLI with CSAR unpackaging command

---

src/opera/commands/deploy.py
src/opera/commands/init.py
src/opera/commands/validate.py
tests/integration/cli_commands/inputs.json
tests/integration/cli_commands/runme.sh

Inputs can be very important for the orchestration process as they
often include various secrets and variables that are used to
authenticate and to deploy applications. Up until now inputs were
passed to the orchestrator as a YAML file with key-value pairs.
To make our TOSCA orchestrator more flexible we can extend inputs
format (this was originally explained in the issue #122). So, with
these changes we are adding the possibility to supply inputs also
in JSON format. This was not very hard because opera already stores
inputs as a JSON file in its storage folder (.opera by default) and
therefore we only had to modify the things for certain CLI commands.
This is the part where --inputs-format CLI option has been brought to
life. It can be used to specify the desired YAML or JSON inputs …

Mention that orchestration inputs can be also passed as JSON

---

examples/intrinsic_functions/service.yaml
src/opera/parser/tosca/v_1_3/collector_mixin.py
tests/integration/misc_tosca_types/modules/node_types/noimpl/noimpl.yaml
tests/integration/misc_tosca_types/modules/node_types/test/test.yaml
tests/integration/misc_tosca_types/service-template.yaml
tests/unit/opera/parser/test_tosca.py

Here we are addressing the issue that has been originally spotted in
#131. There is an additional requirement for property (and parameter
definitions) that has to be satisfied in order to stick with the
TOSCA Simple Profile in YAML version 1.3. Every defined property
should be considered required by default unless its required keyname is
explicitly set to false. With these changes we make sure that the users
will be warned if some required property is missing its value and in
these cases the deployment process will fail. According to that we also
needed to update some of TOSCA templates among the examples and
integration tests as there were required properties that were not used.
Fixes #131.

Make TOSCA properties required by default

---

setup.cfg
setup.py

In order to successfully render our README while publishing on PyPI we
need to specify the format of the README as 'text/markdown'. Without
this publishing on PyPI with twine fails as the format defaults to
rst (reStructuredText). And since we use more friendly md (markdown) for
our README we added long_description_content_type metadata to setup.cfg.

Specify README format in setup.cfg

---

examples/attribute_mapping/service.yaml
src/opera/parser/tosca/v_1_3/node_template.py
src/opera/parser/tosca/v_1_3/range.py
src/opera/template/node.py
src/opera/template/requirement.py
tests/integration/concurrency/service.yaml

These changes correspond to issue #88 that has brought up the problem
when targeting more than one instance via the same requirement. When
the same requirement name occurred among the node type/template
requirements opera proceeded with the deployment and the error was
thrown only when running opera outputs that were accessing properties
and attributes via TOSCA functions which already contain checks for
duplicate capability and requirement names. TOSCA standard also states
that duplicate requirement names within the same TOSCA type or template
shall result in error. So now when duplicate requirement name occurs,
opera raises an exception before the deployment.
_______________________________________________________
Closes #88

Use occurrences keyname to control usage of requirements

---

docs/saas.rst

This adds docs on how to log in with RADON credentials, alongside the instructions for internal auth.
Closes #148.

Fix SaaS CLI docs to use RADON auth

---

requirements.txt
setup.cfg
src/opera/cli.py
src/opera/commands/deploy.py
src/opera/commands/info.py
src/opera/commands/init.py
src/opera/commands/outputs.py
src/opera/commands/package.py
src/opera/commands/undeploy.py
src/opera/commands/unpackage.py
src/opera/commands/validate.py

This PR does the following:
- refactor comment in setup.py 
- add a missing verbose flag to opera package CLI command 
- implement opera tab completion
Shell completion is the most important here.
It seems that [argcomplete](https://github.com/kislyuk/argcomplete) Python package might not be the
best solution for subparsers and also has other drawbacks.
We are able to use [shtab](https://github.com/iterative/shtab) in our code to generate a shell completion
script. And we don't even need a separate command to do that since
shtab supports defining a global optional argument that will print
out the completion script for the main parser. We used that and
defined `--shell-completion/-s` flag which receives a shell type to
generate completion for. Shtab currenty supports bash and zsh so those …

Introduce opera tab completion

---

src/opera/commands/deploy.py
src/opera/commands/init.py
src/opera/commands/package.py
src/opera/commands/unpackage.py
src/opera/commands/validate.py
src/opera/parser/tosca/csar.py
src/opera/utils.py

This restructures the CSAR class a bit so that it's easier to treat file- and directory-based CSARs in the same way. I also added separate meta classes to distinguish between CSAR and service template metadata.

Specialise directory and file based csars in classes

---

src/opera/commands/deploy.py
src/opera/commands/info.py
src/opera/commands/undeploy.py

A WIP because it depends on #153.
Info will now use CSAR metadata to fill out some `info` fields, which will make xopera-saas be able to autofill the service template name even before anything is deployed.

Stateless info

---

src/opera/stdlib/v_1_3.yaml

In #166 we found that `tosca.nodes.Storage.ObjectStorage` TOSCA 
normative type has a maxsize property which is described to be optional 
but its type definition doesn't explicitly set required keyname to false, 
so we had to do it in order to prevent that opera would treat it as a 
required TOSCA property which would be against the standard.
Must be merged after #165.
Fixes #166.

Make maxsize property optional for TOSCA ObjectStorage normative type

---

src/opera/parser/yaml/loader.py

As our YAML parser extends internal functionality, we need to be careful about our dependencies changing internally.
PyYAML moved one of our imports in 5.4 and deprecated the old path.
We now try to use the new, non-deprecated path, falling back the old path if the new one isn't available, which maintains full compatibility with all versions of our dependencies.
Closes #176.

Compatibility with PyYAML>=5.4.

---

src/opera/commands/deploy.py
src/opera/commands/diff.py
src/opera/commands/info.py
src/opera/commands/init.py
src/opera/commands/outputs.py
src/opera/commands/undeploy.py
src/opera/commands/update.py
src/opera/commands/validate.py
tests/integration/misc_tosca_types/modules/node_types/noimpl/noimpl.yaml

This PR applies some CLI updates:
- tab completion for `opera diff` and `opera update`
- save results from `opera outputs` and `opera info` to a file
- update help messages for CLI commands
- add host requirement to `noimpl` node from integration tests
- remove the duplicated archive check in `opera unpackage` command (moved to #179)
Fixes #145, closes #151.

CLI updates: help messages, resolving issues, tab completion update etc.

---

src/opera/stdlib/v_1_3.yaml

In #177 we found that tosca.nodes.Database TOSCA normative type has
a port property which is described to be optional but its type
definition doesn't explicitly set required keyname to false, so we had
to do it in order to prevent that opera would treat it as a required
TOSCA property which would be against the TOSCA standard.
Fixes #177.

Update tosca.nodes.Database normative type definition

---

Pipfile
examples/policy_triggers/playbooks/delete.yaml
examples/policy_triggers/service.yaml
examples/runme.sh
src/opera/compare/instance_comparer.py
src/opera/constants.py
src/opera/error.py
src/opera/instance/base.py
src/opera/instance/node.py
src/opera/instance/relationship.py
src/opera/instance/topology.py
src/opera/parser/tosca/v_1_3/collector_mixin.py
src/opera/parser/tosca/v_1_3/definition_collector_mixin.py
src/opera/parser/tosca/v_1_3/operation_host.py
src/opera/parser/tosca/v_1_3/policy_definition.py
src/opera/parser/tosca/v_1_3/policy_type.py
src/opera/parser/tosca/v_1_3/topology_template.py
src/opera/template/node.py
src/opera/template/operation.py
src/opera/template/policy.py
src/opera/template/relationship.py
src/opera/template/topology.py
src/opera/template/trigger.py
src/opera/threading/node_executor.py
tests/unit/opera/compare/test_instance_compare.py
tests/unit/opera/instance/test_attribute_mapping.py
tests/unit/opera/instance/test_node_policies.py

This PR is preparing all the things that we need to implement the new `opera notify` CLI command (see issue #108):
- Detect invalid Standard and Configure interface operations (fixes #146)
- Use enum classes to store orchestration constants (resolves #158)
- Prepare to include policies to topology
- Use interface_types too when collecting node's interfaces
- Update policy_triggers example
- Apply policies to nodes when creating topology
- Enable getting properties from policies
- Enable invoking triggers with notify functions
- Supply unit tests for applying polices to nodes

Preparation for opera notify

---

src/opera/commands/diff.py
src/opera/commands/update.py
src/opera/utils.py
tests/unit/opera/compare/conftest.py
tests/unit/opera/compare/test_workdir.py

get_template function in utils.py was not retrieveing template from
working directory, but rather from current directory. This commit fixes
that issue.

Fix for diff_instances for different workdirs

---

docs/opera_cli.rst
src/opera/commands/__init__.py
src/opera/commands/notify.py
src/opera/parser/tosca/v_1_3/collector_mixin.py
src/opera/parser/tosca/v_1_3/definition_collector_mixin.py
src/opera/template/node.py
tests/integration/notify/files/notification_scale_down.json
tests/integration/notify/files/notification_scale_up.json
tests/integration/notify/playbooks/configure.yaml
tests/integration/notify/playbooks/create.yaml
tests/integration/notify/playbooks/delete.yaml
tests/integration/notify/playbooks/scale_down.yaml
tests/integration/notify/playbooks/scale_up.yaml
tests/integration/notify/runme.sh
tests/integration/notify/service.yaml

With this PR we will supply new opera CLI command called `opera notify`, which will bring the option to inform the orchestrator about the changes after the deployment and to execute various policy trigger actions (Ansible playbooks). This command will also make possible to implement scaling actions with xOpera. (see #108).
This PR has to be merged after #187. 
Closes #32.

Introduce opera notify

---

src/opera/commands/unpackage.py

This PR has to be merged right before we release opera version `0.6.5` 
because it includes breaking opera API changes (see https://github.com/xlab-si/xopera-opera/pull/175#discussion_r572703294).

Remove duplicated archive check in unpackage command

---

docs/saas.rst

In the previous PR (#197), we have updated the docs for our xOpera
SaaS component with numerous from Eclipse Che. We made a small mistake
because images were referenced with the wrong names in the docs and
were therefore not shown properly. This commit will fix this and will
also update the width for images within documentation, because the
images can be a little but smaller for a better view.

Fix image names for xOpera SaaS docs

---

Pipfile

When pushing our docs to GitHub pages in the last days we were
surprised when some parts were not rendered correctly. We have
discovered that this has something to do with the version of Read the
Docs theme we're using, so we had to upgrade `sphinx-rtd-theme` 
package to 0.5.2 and we have also updated Sphinx to the latest 3.5.3 version.
Apart from that we also needed to set docutils to version 0.16 because doc8
always installs the latest docutils version which is now 0.17 and this one has 
an aforementioned rendering error.

Update Sphinx and Read the Docs dependency

---

src/opera/value.py
tests/unit/opera/instance/test_eval_function.py

Previously TOSCA functions like get_input or concat that were
used inside maps or lists were not evaluated. This commit solves
this issue.

Function evaluation for maps and lists

---

src/opera/commands/info.py
src/opera/parser/tosca/csar.py

Related to #203, and also augments the info output with service template and CSAR metadata, which we're already computing.
If the CSAR is invalid, new data is left empty because parting it relies on the CSAR being valid.

opera info: rendered input values and additional ST/CSAR metadata

---

.gitignore
examples/policy_triggers/service.yaml
src/opera/parser/tosca/v_1_3/node_template.py
tests/integration/concurrency/service.yaml
tests/integration/misc_tosca_types/modules/node_types/test/test.yaml
tests/unit/opera/parser/test_tosca.py

This PR will:
- repair the integration test for concurrency (found in #185)
- implement catching undeclared requirements on node templates (first spotted in #63)
- update integration tests and examples according to requirement changes
- update .gitignore with more files
___________________________
Fixes #185, resolves #63, resolves #182 and resolves #186.

Updates for TOSCA requirements and .gitignore

---

src/opera/commands/validate.py
src/opera/parser/tosca/__init__.py

Preserving existing behaviour, this adds the ability to validate directory-based CSARs.
`opera validate <path>` was changed into `opera validate [path]` with the default being the current directory, which is consistent with other commands.
Related to #204, this makes it easier to determine why `opera info` won't have had a full output. It'll also support me adding a split validate csar/service template option to xopera-saas.

Enable validating directory-based CSARs

---

.circleci/config.yml
.sanity-config.ini
Pipfile
setup.cfg
src/opera/executor/utils.py
src/opera/parser/tosca/csar.py

This PR adds or changes the following things:
- CI workflow that would use Python 3.9 as the executor for sanity, unit and integration tests
- Calculate code coverage only when pushing onto master branch
- Update classifiers from setup.cfg 
- Update package versions in Pipfile
- Refactor code to satisfy pylint
Closes #150.

CI for python 3.9 and some sanity and package updates 

---

src/opera/commands/deploy.py
src/opera/commands/info.py
src/opera/commands/notify.py
src/opera/commands/undeploy.py
src/opera/instance/base.py
src/opera/instance/node.py
src/opera/instance/topology.py
tests/integration/cli_commands/runme.sh

In #203 we found out that orchestration state/status which is returned
by opera info could be improved. This has been done now and xOpera now
provides the following orchestration states (the are also CLI commands
that trigger changing the state in the brackets):
- `initialized` (opera init)
- `deploying` (opera deploy)
- `deployed` (opera deploy)
- `undeploying` (opera undeploy)
- `undeployed` (opera undeploy)
- `error` (opera deploy/undeploy/update/notify)
- `unknown` (for special cases which might happen)
These state are changed during the execution of TOSCA interface
operations (e.g. Ansible playbooks). We had to modify our CLI commands
a little and also our integration tests.

Refactor orchestration states for TOSCA nodes

---

.circleci/config.yml
setup.cfg
src/opera/compare/template_comparer.py
src/opera/instance/base.py
src/opera/instance/node.py
src/opera/parser/tosca/v_1_3/artifact_definition.py
src/opera/parser/tosca/v_1_3/attribute_definition.py
src/opera/parser/tosca/v_1_3/collector_mixin.py
src/opera/parser/tosca/v_1_3/definition_collector_mixin.py
src/opera/parser/tosca/v_1_3/parameter_definition.py
src/opera/parser/tosca/v_1_3/property_definition.py
src/opera/parser/tosca/v_1_3/service_template.py
src/opera/parser/tosca/v_1_3/topology_template.py
src/opera/template/node.py
src/opera/template/operation.py
src/opera/template/topology.py
tests/unit/opera/parser/tosca/test_void.py
tests/unit/opera/parser/yaml/test_loader.py

This PR will:
- add fixes for TOSCA interface operations (see #237)
- add more checks for Standard and Configure TOSCA interface operations
- update outputs for execution of primary implementation artifacts
- update file comparison within template comparer
- remove CI/CD run for Python 3.7
- remove the remaining targeted TODOs
Fixes #237.

Fix parsing for interfaces and some other minor updates
